apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.zookeeper.name }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "kafkahelmdeploy.zookeeperlabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.zookeeper.type }}
  ports:
    - port: {{ .Values.service.zookeeper.port }}
      targetPort: {{ .Values.service.zookeeper.port }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.zookeeper.nodePort }}
  selector:
    {{- include "kafkahelmdeploy.zookeeperselectors" . | nindent 4 }}
